"""add metric_records table

Revision ID: a3bbc96aa556
Revises: 6d9c60853eb7
Create Date: 2026-07-07 21:16:34.119448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3bbc96aa556'
down_revision: Union[str, None] = '6d9c60853eb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('endpoint_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('polled_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('is_healthy', sa.Boolean(), nullable=False),
    sa.Column('error_detail', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['monitored_endpoints.id'], name=op.f('fk_metric_records_endpoint_id_monitored_endpoints'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_metric_records_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_records'))
    )
    op.create_index(op.f('ix_metric_records_endpoint_id'), 'metric_records', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_metric_records_organization_id'), 'metric_records', ['organization_id'], unique=False)
    op.create_index(op.f('ix_metric_records_polled_at'), 'metric_records', ['polled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_records_polled_at'), table_name='metric_records')
    op.drop_index(op.f('ix_metric_records_organization_id'), table_name='metric_records')
    op.drop_index(op.f('ix_metric_records_endpoint_id'), table_name='metric_records')
    op.drop_table('metric_records')
    # ### end Alembic commands ###
